server:
  servlet:
    context-path: /project-management
spring:
  application:
    name: project-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/project-management-system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    locations: classpath:db/migration
domain:
  back: http://localhost:8080/project-management
project:
  security:
    permit-all: /auth/**, /swagger-ui/**, /v3/api-docs/**, /sign-up
jwt:
  secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  expiration-time-minutes: 10