ALTER TABLE task_comments
    DROP CONSTRAINT FK_TASK_COMMENTS_ON_TASK;

ALTER TABLE task_comments
    ADD CONSTRAINT FK_TASK_COMMENTS_ON_TASK FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;